version: '3.4'

services:
  dashboard:
    image: metrics-catalog/dashboard
    container_name: metrics_catalog_dashboard
    build:
      context: dashboard
      dockerfile: Dockerfile
    env_file:
      - .env.dashboard
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - api
    networks:
      - container_network

  api:
    image: metrics-catalog/api
    container_name: metrics_catalog_api
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - .env.api
    ports:
      - "3001:3000"
    depends_on:
      - database
    networks:
      - container_network

  database:
    image: mongo
    container_name: metrics_catalog_db
    ports:
      - "27017:27017"
    networks:
      - container_network

networks:
  container_network:
    driver:
      bridge
